apiVersion: v1
kind: Namespace
metadata:
  name: k8s-demo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo
  namespace: k8s-demo
  labels:
    app: k8s-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-demo
  template:
    metadata:
      labels:
        app: k8s-demo
    spec:
      #      serviceAccount: k8s-demo
      containers:
        - name: k8s-demo
          image: k8s-demo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: k8s-demo
  namespace: k8s-demo
  labels:
    app: k8s-demo
spec:
  #  type: LoadBalancer
  #  type: NodePort
  ports:
    - port: 80
      protocol: TCP
  #      targetPort: 80
  #      nodePort: 30000
  selector:
    app: k8s-demo

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-demo
  namespace: k8s-demo
spec:
  selector:
    app: nginx-demo
  ports:
    - name: http
      port: 8001
      targetPort: 80
      nodePort: 30000
  type: NodePort

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-demo
  namespace: k8s-demo
spec:
  serviceName: nginx-demo
  replicas: 1
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
        - name: nginx-demo
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: k8s-demo
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: k8s-demo
                port:
                  number: 80
